export const accessToketExpireTime = '30000s'
export const refreshToketExpireTime = '1d'
export const roleStudentName = 'Student'
export const roleTeacherName = 'Teacher'
export const roleAdminName = 'Admin'
export const FRONT_BASE_URL = 'http://localhost:3000'
export const PASSWORD_RECOVERY_EXPIRE_TIME = '1h'
