export const accessToketExpireTime = '30000s'
export const refreshToketExpireTime = '1d'
export const roleStudentName = 'Student'
export const roleTeacherName = 'Teacher'
export const roleAdminName = 'Admin'
